global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'miningcore'
    metrics_path: '/metrics'
    scheme: http
    static_configs:
      - targets: ['localhost:4000']  # Using Nginx reverse proxy for MiningCore metrics
