global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'stratum'
    static_configs:
      - targets: ['protocol-bridge:3032']
        labels:
          protocol: 'stratum'

  - job_name: 'miningcore'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.2.100:4000']
        labels:
          instance: 'miningcore'

  - job_name: 'getwork'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['protocol-bridge:8545']
        labels:
          protocol: 'getwork'
